### PR TITLE
Pwolfram/preprocess timeserisstats

### PR DESCRIPTION
**Pull request by pwolfram**
Assorted changes following pwolfram#6

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@pwolfram: not sure what to do with this one. I included a lot of these changes in PR#6 last night (sorry I didn't look closely at this PR until now).

**Comment by pwolfram** [comment]
@milenaveneziani, did you push to your branch?  As far as I can tell these changes should still be applied to your branch.  I'm happy to merge our branches together but will need you to push your latest code before I can do this-- thanks!

**Comment by milenaveneziani** [comment]
@pwolfram , yes, I pushed to the branch on my fork. And the PR was updated.
I did not make the test on yearoffset a function. And there is at least one conflict because I chose yearoffset=1849 (so that 0001-01-01 will correspond to 1850-01-01).

**Comment by pwolfram** [comment]
@milenaveneziani, I think you need to merge this PR before I merge your code.  These are the changes I've identified that we need in the wrapper for clarity going forward.  The reason I made `yearoffset=1850` vs `yearoffset=1849` was because the test case didn't start on 1850, e.g., for `python mpas_xarray.py -f "globalStats*nc"`.

**Pull request merged**
